# This workflow file was modified from here: https://github.com/astral-sh/ruff-action
name: Ruff Linting
on: 
  push:
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1
